// AUTO-GENERATED by scripts/fetch-boss-images.mjs — do not edit by hand.
// Boss ids that have an icon at /public/bosses/<id>.png
export const BOSS_IMAGE_IDS = new Set<string>(["akechi","arkarium","black-mage","crimson-queen","crimson-queen-chaos","cygnus","damien","darknell","frenzied-gigatoad","gigatoad","gloom","hilla","hilla-hard","horntail","kaling","kalos","lotus","lucid","magnus","magnus-hard","omni-cln","papulatus","papulatus-chaos","pierre","pierre-chaos","pink-bean","pink-bean-chaos","princess-no","ranmaru","seren","slime","vellum","vellum-chaos","verus-hilla","von-bon","von-bon-chaos","von-leon","will","yakuza-boss","zakum","zakum-chaos"]);

export function bossImage(id: string): string | null {
  return BOSS_IMAGE_IDS.has(id) ? `/bosses/${id}.png` : null;
}
